<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>daa025d1-517d-4d9e-b7fe-102bb5ed720f</testSuiteGuid>
   <testCaseLink>
      <guid>589d10b9-111a-47a8-aaf9-0e334a7277ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC2.001_Verify_SucessfulUserLogin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>387aa9dc-28a4-40bb-ab7d-2209a71ee8f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC2.002_Verify_UsernamePasswordLoginEmpty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c373a01a-51e4-4e40-b6f4-f9be3014e2cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a5f775-8671-4d66-a8d4-c2a116f9dea0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4c61f23-e40b-4d9e-90c0-750d528de5d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC2.003_VerifyUserNotRegistered</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d3bd93f-f1da-4898-9d1d-e5f72d1bea13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca57da1d-8b54-48f8-8fee-c037ac247dc8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e66cbfd3-57f4-42ba-8b1f-2b965c3564ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC2.004_VerifyWrongPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cebf031-9b1d-4c38-a68d-1ad1c108ef97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3968fef0-f658-454e-bd03-1765658ffb54</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
