<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sign Up</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7cd84d96-2c4d-4334-ac87-7539496f6518</testSuiteGuid>
   <testCaseLink>
      <guid>7771d7bd-3246-4885-8920-b448913f4ef4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/TC1.001_Verify_SuccessfulUserSignUp</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b9e169b-21b7-45cb-81d3-dba17b06ae9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>565f5d5b-ec19-480e-9383-a0c516b4875a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa392242-ad54-491e-8be7-4ae20dbc3b88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/TC1.003_Verify_UsernamePasswordSignUpEmpty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c672b62-16fb-4f1c-8cd0-e1cde0d1396a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db157b88-aa35-4655-b480-5002bfbff726</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3616063-b9c2-4249-aa98-e94082d15b9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/TC1.002_Verify_ExistingUserRegistered</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f44f53ad-145d-4c20-9f56-42ddc0d3908a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9462285f-41d8-4edd-adbc-9a42c6018318</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
